apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    name: web-server
spec:
  selector:
    name: web-server
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 32080
